、name: Daily Checkin

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright
        run: |
          npm init -y
          npm install playwright
          npx playwright install

      - name: Run Checkin
        run: node checkin.js
        env:
          COOKIES: ${{ secrets.COOKIES }}
